language: node_js

node_js:
  - "0.10"

notifications:
  flowdock: ce9d8b10b8bd428f1d59cf0a62915cff

before_install:
  - travis_retry npm install -g npm

install:
  # install required dependencies
  - travis_retry npm install -g grunt-cli
  - travis_retry npm install -g bower
  - travis_retry npm install
  - travis_retry bower install

before_script:
  - grunt compile

  # start node to serve public files
  - node server.js &

script:
  - grunt lint:travis
  - npm test
