language: node_js

node_js:
  - "0.10"

install:
  - npm install -g git+https://AxS4AaP:836e170c40319c4a1f0ada346f644615fc6005d2@github.com/School-Improvement-Network/travis-scripts.git

script:
  - travis lint