language: node_js

node_js:
  - "0.10.28"

notifications:
  flowdock: ce9d8b10b8bd428f1d59cf0a62915cff

before_install:
  - npm install -g npm

install:
  # install required dependencies
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - grunt compile --stack --verbose

  # start node to serve public files
  - node server.js > /dev/null 2>&1 &

script:
  - grunt lint:travis
  - npm test
