language: node_js

node_js:
  - "0.10"

notifications:
  flowdock: ce9d8b10b8bd428f1d59cf0a62915cff

before_install:
  - npm install -g npm

install:
  # install required dependencies
  - npm install -g grunt-cli
  - npm install -g bower
  - npm install
  - bower install

before_script:
  - grunt compile

  # start node to serve public files
  - node server.js &

script:
  - grunt travis-lint
  - npm test